services:
  - type: web
    name: shopproject
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shopproject.wsgi:application
    preDeployCommand: python manage.py migrate && python manage.py collectstatic --noinput