# Generated by Django 4.0 on 2025-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tunnel', 'トンネル'), ('hospital', '廃病院'), ('mountain', '山奥'), ('school', '廃校')], default='tunnel', max_length=50),
        ),
    ]
